name: Deploy to VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}      # 84.201.176.99
          username: ${{ secrets.VM_USER }}  # strbje
          key: ${{ secrets.VM_SSH_KEY }}    # приватный SSH-ключ
          script: |
            bash -lc '
              cd ~/virtual-football-stats

              # записываем .env из секретов (не хранится в репо)
              cat > .env <<EOF
DATABASE_URL=${{ secrets.DATABASE_URL }}
NODE_ENV=production
EOF

              bash scripts/deploy.sh
            '
