name: Deploy to VM

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          port: 22
          script_stop: true          # упадём сразу, если команда на ВМ вернула ненулевой код
          command_timeout: 30m       # потолок на длительность
          envs: NODE_ENV             # проброс переменных, если надо
          script: |
            export NODE_ENV=production
            bash ~/virtual-football-stats/scripts/deploy.sh
