name: Deploy to VM

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            set -euo pipefail

            cd ~/virtual-football-stats

            # всегда подтягиваем чистое состояние из GitHub
            git fetch origin
            git reset --hard origin/main

            # пишем .env из секретов
            printf "DATABASE_URL=%s\nNODE_ENV=production\n" "${{ secrets.DATABASE_URL }}" > .env

            # зависимости + prisma client + сборка
            npm ci --prefer-offline --no-audit --cache ~/.npm
            npx prisma generate --schema=prisma/schema.prisma || true
            npm run build

            # рестарт через pm2
            pm2 startOrRestart ecosystem.config.js --update-env
            pm2 save

            '
